#!/usr/bin/env python3
""" mypixels - A low clutter, python-gtk based terminal emulator.
"""

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Glued together in free time by Filip Volejnik: f.volejnik at google mail
# heavily inspired by uzbl-tabbed.py
# Solarized colors are a great piece of work of Ethan Schoonover
# TODO: Timer for tablist updates - optionally set to refresh if using some dynamic status
# TODO: Write to buffer - a small box floating somewhere that'll display what user's writing (in parallel with the console).
# TODO: Tagging of consoles - and grouping via those tags (partially done with tab coloring)

import gi
from gi import pygtkcompat
gi.require_version('Vte', '2.91')
gi.require_version('GdkPixbuf', '2.0')
# pygtkcompat.enable()
# pygtkcompat.enable_gtk(version='3.0')
import gobject
from gi.repository import Vte, GLib, Gtk, Gdk, Pango, Gio, GdkPixbuf
#import vte
#import pango
import types
import yaml
import os.path
from pathlib import Path
import sys
import html
import traceback
import cairo
from typing import Dict, Any, List, Optional

def clock():
    from time import localtime, strftime
    return "<span foreground = '#966'>%s</span> " % strftime("%H:%M", localtime())

callables = {
    'clock' : clock
    }

max_groups = 8

# Default config
config = {
    'tablist_background': "#303030", # Tablist background
    
    'focus_new_tabs': True,
    'tab_prepend': 'clock', # name of callback function that generates pango markup text appended to tab list before the tabs
    'tab_append': None,  # the same, but appended after tab list
    'tab_format': '<span %(color)s>%(tcorner)s%(entangled)s%(tname)s]</span>', # tid Tab id (unique), tname - tab name, tidx - tab index (from 1 on the left)
    'tab_shorten_str': '\xe2\x80\xa6',
    'tab_color_bg': '#303030',
    'tab_color_bg_selected': '#505020',
    'tab_color_fg': '#888',
    'tab_color_fg_selected': '#fff',
    'tab_color_entangle': '#f00',
    'tab_color_idx': '#808',
    'tablist_font': 'Liberation Mono 7',
    'term_font': 'Terminus 8',
    'default_tab_title': '',
    'scrollback_lines': 1000,
    'term_opacity': 0.1,
    'bg_tint_color': '#140008',
    'foreground_color': '#BBB',
    'background_color': '#000',
    'hide_single_tab': False,
    'tablist_top': True,
    'tab_title_max_length': 16, # -1 to disable this
    'tab_title_short_current': 32, # shorten the selected tab title (False - don't, True - do, int > 0 current title max length)
    'tab_title_shorten_start': False, # shorten so that end of the text is visible, not start
    'tablist_hide': False,
    'default_width': 640,
    'default_height': 480,
    'default_maximize': False,

    'tab_overview_on_alt': True,  # Show tab overview when Alt is held during tab switching
    'tab_overview_opacity': 0.3,  # Background opacity for tab overview (0.0 - 1.0)

    'wal_palette': '~/.cache/wal/colors.yml',

    'palette': '',

    # choosable tab colors (grouping)
    'col_0': '#b58900',
    'col_1': '#cb4b16',
    'col_2': '#dc322f',
    'col_3': '#d33682',
    'col_4': '#6c71c4',
    'col_5': '#268bd2',
    'col_6': '#2aa198',
    'col_7': '#859900',

    'tab_highlight_mod': 'Alt_L',

    'add_button_color': '#FFA500', # Default color for the add new tab button

    'bindings': {
        'move_prev_tab' : 'MOD1+SHIFT+Left',
        'move_next_tab' : 'MOD1+SHIFT+Right',
        'move_first_tab': 'MOD1+SHIFT+Home',
        'move_last_tab' : 'MOD1+SHIFT+End',

        'prev_tab': ('MOD1+Left', 'MOD1+SHIFT+f'),
        'next_tab': ('MOD1+Right', 'MOD1+SHIFT+b'),
        'first_tab': 'MOD1+Home',
        'last_tab': 'MOD1+End',

        'close_tab': ('CONTROL+ALT+x', 'CONTROL+ALT+q'),
        'new_tab': ('CONTROL+ALT+z', 'CONTROL+SHIFT+t'),
        'new_window': 'CONTROL+SHIFT+n',

        'shrink_font': 'MOD1+SHIFT+KP_Subtract',
        'enlarge_font': 'MOD1+SHIFT+KP_Add',

        'toggle_hide_tabs': 'CONTROL+SHIFT+v',

        'prev_color': 'MOD1+SHIFT+braceleft',
        'next_color': 'MOD1+SHIFT+braceright',

        'toggle_entangle': 'MOD1+SHIFT+KP_Multiply',

        'rename_tab': 'MOD1+SHIFT+n',

        'show_search': 'MOD1+SHIFT+s',

        'search_prev': 'MOD1+SHIFT+a',
        'search_next': 'MOD1+SHIFT+d',

        'font_selector': 'CONTROL+SHIFT+f',

        'config_reload': 'CONTROL+SHIFT+r',

        'show_tab_overview': 'MOD1+o',

        'goto_tab_0': 'MOD1+_1',
        'goto_tab_1': 'MOD1+_2',
        'goto_tab_2': 'MOD1+_3',
        'goto_tab_3': 'MOD1+_4',
        'goto_tab_4': 'MOD1+_5',
        'goto_tab_5': 'MOD1+_6',
        'goto_tab_6': 'MOD1+_7',
        'goto_tab_7': 'MOD1+_8',
        'goto_tab_8': 'MOD1+_9',
        'goto_tab_9': 'MOD1+_0'
    }
};

# Used for quick selection via <Mod1>[0-9]
num2key = (
    Gdk.KEY_1,
    Gdk.KEY_2,
    Gdk.KEY_3,
    Gdk.KEY_4,
    Gdk.KEY_5,
    Gdk.KEY_6,
    Gdk.KEY_7,
    Gdk.KEY_8,
    Gdk.KEY_9,
    Gdk.KEY_0,
    );

str2mod = {
    'mod1':  Gdk.ModifierType.MOD1_MASK,
    'alt':  Gdk.ModifierType.MOD1_MASK,
    'shift': Gdk.ModifierType.SHIFT_MASK,
    'control': Gdk.ModifierType.CONTROL_MASK,
    'ctrl': Gdk.ModifierType.CONTROL_MASK
}
# parses mod+mod+key
def key_press_parse(bindstr):
    key = None
    mods = 0

    for kp in bindstr.split('+'):
        kl = kp.lower()
        if kl in str2mod:
            mods = mods | str2mod[kl]
        else:
            if not key:
                key = Gdk.keyval_from_name(kp)
            else:
                print("Parse error: '%s' - part '%s', state %s, %s" % (bindstr, kp, str(key), str(mods)))

    return (mods, key)

def parse_rgba(color):
    col = Gdk.RGBA()
    col.parse(color)
    return col

def brighten(strcolor, amount = 1.2):
    col = parse_rgba(strcolor)
    return '#{:02x}{:02x}{:02x}'.format(min(255, int(255 * col.red * amount)),
                                        min(255, int(255 * col.green * amount)),
                                        min(255, int(255 * col.blue * amount)))

# parses key_combo=call(arg)
def key_bind_parse(bindstr):
    pass

def validate_color(color_str: str) -> bool:
    """Validate that a string is a valid color format"""
    try:
        col = Gdk.RGBA()
        return col.parse(color_str)
    except:
        return False

def validate_config(cfg: Dict[str, Any]) -> List[str]:
    """Validate configuration and return list of warnings/errors

    Returns:
        List of warning/error messages (empty if all valid)
    """
    warnings = []

    # Validate colors
    color_keys = [
        'tablist_background', 'tab_color_bg', 'tab_color_bg_selected',
        'tab_color_fg', 'tab_color_fg_selected', 'tab_color_entangle',
        'tab_color_idx', 'bg_tint_color', 'foreground_color', 'background_color',
        'add_button_color'
    ]
    for i in range(max_groups):
        color_keys.append(f'col_{i}')

    for key in color_keys:
        if key in cfg and not validate_color(cfg[key]):
            warnings.append(f"Invalid color value for '{key}': {cfg[key]}")

    # Validate numeric ranges
    numeric_validations = {
        'scrollback_lines': (0, 100000, "must be between 0 and 100000"),
        'term_opacity': (0.0, 1.0, "must be between 0.0 and 1.0"),
        'tab_overview_opacity': (0.0, 1.0, "must be between 0.0 and 1.0"),
        'default_width': (100, 10000, "must be between 100 and 10000"),
        'default_height': (100, 10000, "must be between 100 and 10000"),
        'tab_title_max_length': (-1, 1000, "must be between -1 (unlimited) and 1000"),
    }

    for key, (min_val, max_val, msg) in numeric_validations.items():
        if key in cfg:
            val = cfg[key]
            if not isinstance(val, (int, float)) or val < min_val or val > max_val:
                warnings.append(f"Config '{key}' {msg}, got: {val}")

    # Validate boolean values
    bool_keys = [
        'focus_new_tabs', 'hide_single_tab', 'tablist_top', 'tab_title_shorten_start',
        'tablist_hide', 'default_maximize', 'tab_overview_on_alt'
    ]
    for key in bool_keys:
        if key in cfg and not isinstance(cfg[key], bool):
            warnings.append(f"Config '{key}' must be boolean (true/false), got: {cfg[key]}")

    # Validate font descriptions
    for font_key in ['tablist_font', 'term_font']:
        if font_key in cfg:
            try:
                desc = Pango.FontDescription(cfg[font_key])
                if not desc.get_family():
                    warnings.append(f"Invalid font description for '{font_key}': {cfg[font_key]}")
            except:
                warnings.append(f"Cannot parse font description for '{font_key}': {cfg[font_key]}")

    # Validate file paths
    if 'wal_palette' in cfg and cfg['wal_palette']:
        path = Path(cfg['wal_palette']).expanduser()
        if not path.exists() and not path.parent.exists():
            warnings.append(f"Wal palette parent directory doesn't exist: {cfg['wal_palette']}")

    # Validate key bindings
    if 'bindings' in cfg:
        for action, binding in cfg['bindings'].items():
            bindings_list = binding if isinstance(binding, (list, tuple)) else [binding]
            for bind_str in bindings_list:
                try:
                    mods, key = key_press_parse(bind_str)
                    if key is None or key == 0:
                        warnings.append(f"Invalid key binding for '{action}': {bind_str}")
                except Exception as e:
                    warnings.append(f"Cannot parse key binding for '{action}': {bind_str} - {e}")

    return warnings

# stolen from Terminator https://github.com/m45t3r/t3rminator/blob/master/terminatorlib/terminator.py
def eventkey2gdkevent(eventkey):  # FIXME FOR GTK3: is there a simpler way of casting from specific EventKey to generic (union) GdkEvent?
    gdkevent = Gdk.Event(eventkey.type)
    gdkevent.key.type = eventkey.type
    gdkevent.key.window = eventkey.window
    gdkevent.key.send_event = eventkey.send_event
    gdkevent.key.time = eventkey.time
    gdkevent.key.state = eventkey.state
    gdkevent.key.keyval = eventkey.keyval
    gdkevent.key.length = eventkey.length
    gdkevent.key.string = eventkey.string
    gdkevent.key.hardware_keycode = eventkey.hardware_keycode
    gdkevent.key.group = eventkey.group
    gdkevent.key.is_modifier = eventkey.is_modifier
    return gdkevent

def counter():
    """ Tab ID generator """
    i = 1
    while True:
        yield i
        i += 1

class TabOverview:
    """Standalone tab overview/switcher class"""

    def __init__(self, parent_window, overlay, notebook, tabs_dict, entangled_list, config, mypixels_instance):
        self.window = parent_window
        self.overlay = overlay
        self.notebook = notebook
        self.tabs = tabs_dict
        self.entangled = entangled_list
        self.config = config
        self.mypixels = mypixels_instance

        self.active = False
        self.selected = 0
        self.mode = 'standalone'  # 'standalone' or 'switcher'

        self.overview_box = None
        self.overview_bg_box = None
        self.overview_tiles = []

        # Cache for terminal snapshots
        self.snapshot_cache = {}
        self.cache_timestamp = 0

        # Timer for periodic updates in switcher mode
        self.update_timer_id = None

        # Key bindings for standalone mode
        self.setup_keybinds()

    def setup_keybinds(self):
        """Setup key bindings for standalone mode"""
        self.keybinds = {
            'close_tab': (Gdk.KEY_x, Gdk.ModifierType.CONTROL_MASK | Gdk.ModifierType.MOD1_MASK),
            'close_tab_alt': (Gdk.KEY_q, Gdk.ModifierType.CONTROL_MASK | Gdk.ModifierType.MOD1_MASK),
            'new_tab': (Gdk.KEY_z, Gdk.ModifierType.CONTROL_MASK | Gdk.ModifierType.MOD1_MASK),
            'new_tab_alt': (Gdk.KEY_t, Gdk.ModifierType.CONTROL_MASK | Gdk.ModifierType.SHIFT_MASK),
        }

    def capture_terminal_snapshot(self, terminal):
        """Capture a snapshot of the terminal widget"""
        alloc = terminal.get_allocation()
        width = alloc.width
        height = alloc.height

        if width <= 0 or height <= 0:
            return None

        surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
        context = cairo.Context(surface)
        terminal.draw(context)
        pixbuf = Gdk.pixbuf_get_from_surface(surface, 0, 0, width, height)

        return pixbuf

    def update_snapshot_cache(self, force=False):
        """Update snapshot cache for all tabs

        Args:
            force: If True, bypass the time throttle
        """
        import time
        current_time = time.time()

        # Only update cache if more than 0.5 seconds have passed (unless forced)
        if not force and current_time - self.cache_timestamp < 0.5:
            return False

        self.cache_timestamp = current_time
        current_page = self.notebook.get_current_page()

        # Capture current tab (always visible) - key by terminal widget
        if current_page >= 0:
            tab = self.notebook.get_nth_page(current_page)
            pixbuf = self.capture_terminal_snapshot(tab)
            if pixbuf:
                self.snapshot_cache[tab] = pixbuf

        return False  # For GLib.timeout_add

    def get_cached_or_capture(self, terminal):
        """Get cached snapshot or capture new one

        Args:
            terminal: The VTE terminal widget to capture

        Returns:
            GdkPixbuf or None
        """
        # Try to get from cache first (keyed by terminal widget)
        if terminal in self.snapshot_cache:
            return self.snapshot_cache[terminal]

        # Try to capture (will only work if visible)
        pixbuf = self.capture_terminal_snapshot(terminal)
        if pixbuf:
            self.snapshot_cache[terminal] = pixbuf
        return pixbuf

    def invalidate_cache(self, terminal=None):
        """Invalidate snapshot cache

        Args:
            terminal: Specific terminal to invalidate, or None for all
        """
        if terminal is None:
            self.snapshot_cache.clear()
        elif terminal in self.snapshot_cache:
            del self.snapshot_cache[terminal]

    def periodic_update_callback(self):
        """Periodic callback to update active tab preview in switcher mode

        Returns:
            True to continue the timer, False to stop
        """
        if not self.active or self.mode != 'switcher':
            self.update_timer_id = None
            return False

        # Capture and update the current tab
        current_page = self.notebook.get_current_page()
        if current_page >= 0:
            tab = self.notebook.get_nth_page(current_page)
            pixbuf = self.capture_terminal_snapshot(tab)
            if pixbuf:
                self.snapshot_cache[tab] = pixbuf
                self.update_tile_image(current_page)

        return True  # Continue the timer

    def show(self, mode='standalone'):
        """Show tab overview

        Args:
            mode: 'standalone' for full control, 'switcher' for Alt-held mode
        """
        # If already active, check if we're switching modes
        if self.active:
            if self.mode == mode:
                # Same mode, toggle off
                self.hide()
                return
            else:
                # Different mode, switch to new mode
                self.hide()

        n_pages = self.notebook.get_n_pages()
        if n_pages == 0:
            return

        # Capture fresh snapshot of active tab before showing
        current_page = self.notebook.get_current_page()
        if current_page >= 0:
            tab = self.notebook.get_nth_page(current_page)
            pixbuf = self.capture_terminal_snapshot(tab)
            if pixbuf:
                self.snapshot_cache[tab] = pixbuf

        self.active = True
        self.mode = mode
        self.selected = current_page

        # Create main container
        main_vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10)

        # Add mode indicator at the top
        mode_label = Gtk.Label()
        mode_label.set_use_markup(True)

        # Get font from config
        fontdesc = Pango.FontDescription(self.config["tablist_font"])
        font_size_in_pt = fontdesc.get_size() / Pango.SCALE
        font_family = fontdesc.get_family()

        if mode == 'standalone':
            mode_text = f'<span font_family="{font_family}" size="{int(font_size_in_pt * 2)}pt" foreground="#4a9a9a"><b>TAB OVERVIEW MODE</b></span>\n<span font_family="{font_family}" size="{int(font_size_in_pt * 1.2)}pt" foreground="#888">ESC: exit | Enter: select | Arrows: navigate | Shift+Arrows: move tab | Ctrl+Alt+X: close | Ctrl+Alt+Z: new tab</span>'
        else:
            mode_text = f'<span font_family="{font_family}" size="{int(font_size_in_pt * 1.5)}pt" foreground="#888"><b>Tab Switcher</b></span>'
        mode_label.set_markup(mode_text)
        mode_label.set_margin_bottom(10)
        main_vbox.pack_start(mode_label, False, False, 0)

        # Create overview container
        self.overview_box = Gtk.Grid()
        self.overview_box.set_row_spacing(10)
        self.overview_box.set_column_spacing(10)
        self.overview_box.set_margin_start(20)
        self.overview_box.set_margin_end(20)
        self.overview_box.set_margin_top(0)
        self.overview_box.set_margin_bottom(20)
        self.overview_box.set_halign(Gtk.Align.CENTER)
        self.overview_box.set_valign(Gtk.Align.CENTER)

        main_vbox.pack_start(self.overview_box, True, True, 0)

        # Create event box for background
        bg_box = Gtk.EventBox()
        bg_box.set_name("overview-background")
        bg_box.add(main_vbox)

        # Calculate grid dimensions
        import math
        cols = math.ceil(math.sqrt(n_pages * 1.5))
        rows = math.ceil(n_pages / cols)

        # Calculate thumbnail size
        window_width = self.window.get_allocated_width()
        window_height = self.window.get_allocated_height()
        available_width = window_width - 100
        available_height = window_height - 100
        thumb_width = min(400, (available_width // cols) - 20)
        thumb_height = min(300, (available_height // rows) - 60)

        self.overview_tiles = []

        # Create tiles for each tab
        for idx in range(n_pages):
            tab = self.notebook.get_nth_page(idx)
            row = idx // cols
            col = idx % cols

            tile_box = Gtk.EventBox()
            tile_box.set_name("overview-tile")
            tile_box.set_events(Gdk.EventMask.BUTTON_PRESS_MASK)

            # Only connect click handler in standalone mode
            if mode == 'standalone':
                tile_box.connect("button-press-event", self.on_tile_clicked, idx)

            tile_vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=5)
            tile_vbox.set_margin_start(10)
            tile_vbox.set_margin_end(10)
            tile_vbox.set_margin_top(10)
            tile_vbox.set_margin_bottom(10)

            # Get tab title
            if tab in self.tabs:
                params = self.tabs[tab]
                title = params.get("name", params.get("title", ""))
            else:
                title = ""

            if not title:
                title = f"Tab {idx + 1}"

            if len(title) > 30:
                title = title[:27] + "..."

            # Create header with label
            header_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=5)
            header_box.set_halign(Gtk.Align.CENTER)

            # Color indicator
            if tab in self.tabs and "group" in self.tabs[tab]:
                grp = self.tabs[tab]["group"]
                color_indicator = Gtk.Label()
                color_indicator.set_markup(f'<span foreground="{self.config["col_" + str(grp)]}">\u25cf</span>')
                header_box.pack_start(color_indicator, False, False, 0)

            # Create label
            label_text = f"<b>{idx + 1}</b>: {html.escape(title)}"
            label = Gtk.Label()
            label.set_use_markup(True)
            label.set_markup(label_text)
            label.set_line_wrap(True)
            label.set_max_width_chars(30)
            label.set_justify(Gtk.Justification.CENTER)

            header_box.pack_start(label, True, True, 0)
            tile_vbox.pack_start(header_box, False, False, 0)

            # Terminal snapshot with overlay for close button
            preview_overlay = Gtk.Overlay()

            # Terminal snapshot (use cache if available, keyed by terminal widget)
            pixbuf = self.get_cached_or_capture(tab)
            if pixbuf:
                scaled_pixbuf = pixbuf.scale_simple(
                    thumb_width, thumb_height,
                    GdkPixbuf.InterpType.BILINEAR
                )
                image = Gtk.Image.new_from_pixbuf(scaled_pixbuf)
                image.set_name(f"terminal-preview-{idx}")
                preview_overlay.add(image)
            else:
                placeholder = Gtk.Label()
                placeholder.set_markup("<i>Preview unavailable</i>")
                placeholder.set_size_request(thumb_width, thumb_height)
                preview_overlay.add(placeholder)

            # Add close button overlaid on top right corner
            close_button = Gtk.Button()
            close_button.set_label("\u00d7")  # × symbol
            close_button.set_name("overview-close-button")
            close_button.set_relief(Gtk.ReliefStyle.NONE)
            close_button.set_halign(Gtk.Align.END)
            close_button.set_valign(Gtk.Align.START)
            close_button.set_margin_top(5)
            close_button.set_margin_end(5)
            close_button.connect("clicked", self.on_close_button_clicked, idx)
            preview_overlay.add_overlay(close_button)

            tile_vbox.pack_start(preview_overlay, True, True, 0)

            # Entangled indicator
            if tab in self.entangled:
                entangled_label = Gtk.Label()
                entangled_label.set_markup(f'<span foreground="{self.config["tab_color_entangle"]}">*entangled*</span>')
                tile_vbox.pack_start(entangled_label, False, False, 0)

            tile_box.add(tile_vbox)
            self.overview_box.attach(tile_box, col, row, 1, 1)
            self.overview_tiles.append(tile_box)

        # Apply CSS for background and tile styling
        opacity = self.config.get('tab_overview_opacity', 0.85)

        css = f"""
        #overview-background {{
            background-color: rgba(0, 0, 0, {opacity});
        }}
        #overview-tile {{
            border: 2px solid #444;
            border-radius: 5px;
            background-color: rgba(26, 26, 26, 0.9);
            min-width: 200px;
            min-height: 100px;
        }}
        #overview-tile label {{
            color: #ccc;
        }}
        #overview-tile-selected {{
            background-color: rgba(42, 90, 90, 0.9);
            border: 3px solid #4a9a9a;
            border-radius: 5px;
            min-width: 200px;
            min-height: 100px;
        }}
        #overview-tile-selected label {{
            color: #fff;
        }}
        #overview-close-button {{
            background-color: rgba(40, 40, 40, 0.85);
            color: #fff;
            border: 1px solid rgba(180, 60, 60, 0.6);
            border-radius: 4px;
            font-size: 16px;
            font-weight: bold;
            min-width: 28px;
            min-height: 28px;
            padding: 0px;
            margin: 0px;
            opacity: 0.7;
        }}
        #overview-close-button:hover {{
            background-color: rgba(200, 60, 60, 0.95);
            border-color: rgba(220, 80, 80, 1.0);
            opacity: 1.0;
        }}
        """

        style_provider = Gtk.CssProvider()
        style_provider.load_from_data(css.encode())
        Gtk.StyleContext.add_provider_for_screen(
            Gdk.Screen.get_default(),
            style_provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION + 1
        )

        self.overlay.add_overlay(bg_box)
        bg_box.show_all()
        self.overview_bg_box = bg_box

        self.update_selection()

        # Start periodic updates in switcher mode
        if mode == 'switcher':
            # Update every 1000ms (1 second)
            self.update_timer_id = GLib.timeout_add(1000, self.periodic_update_callback)

    def hide(self):
        """Hide the tab overview"""
        if not self.active:
            return

        self.active = False

        # Cancel periodic update timer if running
        if self.update_timer_id is not None:
            GLib.source_remove(self.update_timer_id)
            self.update_timer_id = None

        if self.overview_bg_box:
            self.overlay.remove(self.overview_bg_box)
            self.overview_bg_box = None
        self.overview_tiles = []

        # Refocus current tab in standalone mode
        if self.mode == 'standalone':
            current_page = self.notebook.get_current_page()
            if current_page >= 0:
                tab = self.notebook.get_nth_page(current_page)
                tab.grab_focus()

    def update_selection(self, new_index=None):
        """Update visual indication of selected tile"""
        if not self.active or not self.overview_tiles:
            return

        if new_index is not None:
            self.selected = new_index

        for idx, tile in enumerate(self.overview_tiles):
            if idx == self.selected:
                tile.set_name("overview-tile-selected")
            else:
                tile.set_name("overview-tile")

    def update_tile_image(self, tab_index):
        """Update the image of a specific tile

        Args:
            tab_index: Index of the tab to update
        """
        if not self.active or not self.overview_tiles:
            return

        if tab_index < 0 or tab_index >= len(self.overview_tiles):
            return

        # Get the terminal widget
        tab = self.notebook.get_nth_page(tab_index)
        if tab not in self.snapshot_cache:
            return

        # Find the image widget in the tile and update it
        tile_box = self.overview_tiles[tab_index]
        tile_vbox = tile_box.get_child()
        if not tile_vbox:
            return

        # Find the Gtk.Overlay that contains the image
        preview_overlay = None
        for child in tile_vbox.get_children():
            if isinstance(child, Gtk.Overlay):
                preview_overlay = child
                break

        if not preview_overlay:
            return

        # Get the first child of the overlay (the image or placeholder)
        image = preview_overlay.get_child()
        if not isinstance(image, Gtk.Image):
            return

        # Update the image
        pixbuf = self.snapshot_cache[tab]
        # Calculate thumbnail size
        n_pages = self.notebook.get_n_pages()
        import math
        cols = math.ceil(math.sqrt(n_pages * 1.5))
        rows = math.ceil(n_pages / cols)
        window_width = self.window.get_allocated_width()
        window_height = self.window.get_allocated_height()
        available_width = window_width - 100
        available_height = window_height - 100
        thumb_width = min(400, (available_width // cols) - 20)
        thumb_height = min(300, (available_height // rows) - 60)

        scaled_pixbuf = pixbuf.scale_simple(
            thumb_width, thumb_height,
            GdkPixbuf.InterpType.BILINEAR
        )
        image.set_from_pixbuf(scaled_pixbuf)

    def handle_key(self, event):
        """Handle keyboard navigation (standalone mode only)

        Returns True if handled, False otherwise
        """
        if not self.active or self.mode != 'standalone':
            return False

        keyval = event.keyval
        mods = event.state & Gtk.accelerator_get_default_mod_mask()
        n_pages = self.notebook.get_n_pages()

        import math
        cols = math.ceil(math.sqrt(n_pages * 1.5))

        # Check for close tab keybinds
        close_key, close_mods = self.keybinds['close_tab']
        close_key_alt, close_mods_alt = self.keybinds['close_tab_alt']

        if (keyval == close_key and mods == close_mods) or \
           (keyval == close_key_alt and mods == close_mods_alt):
            # Close the selected tab
            if self.selected >= 0 and self.selected < n_pages:
                self.notebook.remove_page(self.selected)
                # Refresh the overview
                new_n_pages = self.notebook.get_n_pages()
                if new_n_pages == 0:
                    self.hide()
                else:
                    # Adjust selection if needed
                    if self.selected >= new_n_pages:
                        self.selected = new_n_pages - 1
                    # Refresh overview
                    self.hide()
                    self.show(mode='standalone')
            return True

        # Check for new tab keybinds
        new_key, new_mods = self.keybinds['new_tab']
        new_key_alt, new_mods_alt = self.keybinds['new_tab_alt']

        if (keyval == new_key and mods == new_mods) or \
           (keyval == new_key_alt and mods == new_mods_alt):
            # Create new tab
            self.mypixels.new_tab()
            # Refresh overview to show new tab
            self.hide()
            self.show(mode='standalone')
            return True

        if keyval == Gdk.KEY_Escape:
            self.hide()
            return True
        elif keyval == Gdk.KEY_Return or keyval == Gdk.KEY_KP_Enter:
            self.notebook.set_current_page(self.selected)
            self.hide()
            return True
        elif keyval == Gdk.KEY_Left:
            if mods & Gdk.ModifierType.SHIFT_MASK:
                # Shift+Left: Move tab left
                if self.selected > 0:
                    tab = self.notebook.get_nth_page(self.selected)
                    self.notebook.reorder_child(tab, self.selected - 1)
                    self.selected -= 1
                    # Refresh overview
                    self.hide()
                    self.show(mode='standalone')
            else:
                # Left: Navigate left
                if self.selected > 0:
                    self.update_selection(self.selected - 1)
            return True
        elif keyval == Gdk.KEY_Right:
            if mods & Gdk.ModifierType.SHIFT_MASK:
                # Shift+Right: Move tab right
                if self.selected < n_pages - 1:
                    tab = self.notebook.get_nth_page(self.selected)
                    self.notebook.reorder_child(tab, self.selected + 1)
                    self.selected += 1
                    # Refresh overview
                    self.hide()
                    self.show(mode='standalone')
            else:
                # Right: Navigate right
                if self.selected < n_pages - 1:
                    self.update_selection(self.selected + 1)
            return True
        elif keyval == Gdk.KEY_Up:
            if mods & Gdk.ModifierType.SHIFT_MASK:
                # Shift+Up: Move tab up (towards beginning)
                if self.selected >= cols:
                    tab = self.notebook.get_nth_page(self.selected)
                    new_pos = self.selected - cols
                    self.notebook.reorder_child(tab, new_pos)
                    self.selected = new_pos
                    # Refresh overview
                    self.hide()
                    self.show(mode='standalone')
            else:
                # Up: Navigate up
                if self.selected >= cols:
                    self.update_selection(self.selected - cols)
            return True
        elif keyval == Gdk.KEY_Down:
            if mods & Gdk.ModifierType.SHIFT_MASK:
                # Shift+Down: Move tab down (towards end)
                if self.selected + cols < n_pages:
                    tab = self.notebook.get_nth_page(self.selected)
                    new_pos = self.selected + cols
                    self.notebook.reorder_child(tab, new_pos)
                    self.selected = new_pos
                    # Refresh overview
                    self.hide()
                    self.show(mode='standalone')
            else:
                # Down: Navigate down
                if self.selected + cols < n_pages:
                    self.update_selection(self.selected + cols)
            return True
        elif keyval == Gdk.KEY_Home:
            self.update_selection(0)
            return True
        elif keyval == Gdk.KEY_End:
            self.update_selection(n_pages - 1)
            return True
        elif keyval >= Gdk.KEY_1 and keyval <= Gdk.KEY_9:
            idx = keyval - Gdk.KEY_1
            if idx < n_pages:
                self.notebook.set_current_page(idx)
                self.hide()
            return True
        elif keyval == Gdk.KEY_0:
            if n_pages > 9:
                self.notebook.set_current_page(9)
                self.hide()
            return True

        return False

    def on_tile_clicked(self, widget, event, tab_index):
        """Handle mouse click on tile (standalone mode only)"""
        if event.button == 1 and self.mode == 'standalone':
            self.notebook.set_current_page(tab_index)
            self.hide()

    def on_close_button_clicked(self, button, tab_index):
        """Handle close button click in standalone mode"""
        n_pages = self.notebook.get_n_pages()
        if tab_index >= 0 and tab_index < n_pages:
            self.notebook.remove_page(tab_index)
            # Refresh the overview or hide if no tabs left
            new_n_pages = self.notebook.get_n_pages()
            if new_n_pages == 0:
                self.hide()
            else:
                # Adjust selection if needed
                if self.selected >= new_n_pages:
                    self.selected = new_n_pages - 1
                # Refresh overview
                self.hide()
                self.show(mode='standalone')

def dialog_get_text(parent, message, default=''):
    """
    Display a dialog with a text entry.
    Returns the text, or None if canceled.
    """
    d = Gtk.MessageDialog(transient_for=parent,
                          modal=True,
                          destroy_with_parent=True,
                          message_type=Gtk.MessageType.QUESTION,
                          buttons=Gtk.ButtonsType.OK_CANCEL,
                          text=message)
    entry = Gtk.Entry()
    entry.set_text(default)
    entry.show()
    d.vbox.pack_end(entry, False, False, 0)
    entry.connect('activate', lambda _: d.response(Gtk.ResponseType.OK))
    d.set_default_response(Gtk.ResponseType.OK)

    r = d.run()
    text = entry.get_text()
    d.destroy()
    if r == Gtk.ResponseType.OK:
        return text
    else:
        return None


class TabList:
    """Manages the tab list/bar display"""

    def __init__(self, notebook, tabs_dict, entangled_list, config_dict, on_tab_switch_state):
        """Initialize TabList

        Args:
            notebook: The Gtk.Notebook containing tabs
            tabs_dict: Dictionary mapping terminal widgets to tab metadata
            entangled_list: List of entangled terminals
            config_dict: Configuration dictionary
            on_tab_switch_state: Function returning current tab switch state
        """
        self.notebook = notebook
        self.tabs = tabs_dict
        self.entangled = entangled_list
        self.config = config_dict
        self.get_on_tabswitch = on_tab_switch_state

        # Create the container for tabs
        self.container = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
        self.container.set_halign(Gtk.Align.START)
        self.container.set_valign(Gtk.Align.START)

        # Event box wrapper
        self.ebox = Gtk.EventBox()
        self.ebox.set_name("tabbar")
        self.ebox.add(self.container)
        self.ebox.show()  # Show the tab bar widget
        self.container.show()

        # Callbacks
        self.on_tab_clicked_cb = None
        self.on_add_tab_cb = None

    def get_widget(self):
        """Get the EventBox widget containing the tab list"""
        return self.ebox

    def set_callbacks(self, on_tab_clicked, on_add_tab):
        """Set callbacks for user interactions

        Args:
            on_tab_clicked: Callback(tab_index) when tab is clicked
            on_add_tab: Callback() when add button is clicked
        """
        self.on_tab_clicked_cb = on_tab_clicked
        self.on_add_tab_cb = on_add_tab

    def update(self, force_hide=False):
        """Update the tab list display

        Args:
            force_hide: If True, hide the tab list
        """
        # Clear existing tabs
        for child in self.container.get_children():
            self.container.remove(child)

        n_pages = self.notebook.get_n_pages()

        if (n_pages <= 1 and self.config["hide_single_tab"]) or force_hide:
            self.ebox.hide()
            return

        self.ebox.show()

        # Prepend callable if configured
        if self.config.get('tab_prepend'):
            prepend_label = Gtk.Label()
            prepend_label.set_use_markup(True)
            prepend_label.set_markup(callables[self.config['tab_prepend']]())
            self.container.pack_start(prepend_label, False, False, 0)
            prepend_label.show()

        # Add the [+] button
        add_tab_event_box = Gtk.EventBox()
        add_tab_event_box.set_name("add-tab-button")
        add_tab_event_box.set_events(Gdk.EventMask.BUTTON_PRESS_MASK)
        add_tab_event_box.connect("button-press-event", self._on_add_tab_clicked)
        add_tab_event_box.set_tooltip_text("Create a new tab")

        add_tab_label = Gtk.Label()
        add_tab_label.set_markup("[+]")
        add_tab_label.set_margin_top(2)
        add_tab_label.set_margin_bottom(2)
        add_tab_label.get_style_context().add_class("tab-label")

        add_tab_event_box.add(add_tab_label)
        add_tab_event_box.show_all()
        self.container.pack_start(add_tab_event_box, False, False, 0)

        curidx = self.notebook.get_current_page()
        on_tabswitch = self.get_on_tabswitch()

        tab_format = self.config['tab_format']
        max_title_len = self.config['tab_title_max_length']
        tabl_short = self.config['tab_shorten_str']

        for idx, tab in enumerate(self.notebook):
            colfg = self.config["tab_color_fg"]
            colbg = self.config["tab_color_bg"]

            tid = idx + 1
            tidx = f"<span foreground=\"{self.config['tab_color_idx']}\">{tid}</span>"
            tname = ""

            tcorner = "["
            if on_tabswitch:
                tcorner = tidx

            if tab in self.tabs:
                params = self.tabs[tab]
                tid = params["id"]
                tname = params["title"]
                if "name" in params:
                    tname = params["name"]

            if not tname:
                tname = str(tid)

            # Shorten title for non-current tabs
            if idx != curidx:
                if max_title_len > 0 and len(tname) > max_title_len:
                    if self.config['tab_title_shorten_start']:
                        tname = tabl_short + tname[len(tname)-max_title_len:]
                    else:
                        tname = tname[:max_title_len] + tabl_short
            else:
                colfg = self.config["tab_color_fg_selected"]
                colbg = self.config["tab_color_bg_selected"]

                mt_cur = max_title_len
                sh_cur = self.config['tab_title_short_current']

                if isinstance(sh_cur, int):
                    mt_cur = sh_cur
                    sh_cur = True

                if sh_cur and mt_cur > 0 and len(tname) > mt_cur:
                   if self.config['tab_title_shorten_start']:
                       tname = tabl_short + tname[len(tname) - mt_cur:]
                   else:
                       tname = tname[:mt_cur] + tabl_short

            # Apply group color override if set
            if tab in self.tabs:
                grp = self.tabs[tab].get("group", None)
            else:
                grp = None

            if tab in self.entangled:
                entangled = f"<span foreground=\"{self.config['tab_color_entangle']}\">*</span>"
            else:
                entangled = ""

            if grp:
                colfg = self.config[f"col_{grp}"]

            color = f"foreground=\"{colfg}\" background=\"{colbg}\""

            # Escape HTML in title
            tname = html.escape(tname)

            # Create tab event box
            tab_event_box = Gtk.EventBox()
            tab_event_box.set_name(f"tab-{idx}")
            tab_event_box.set_events(Gdk.EventMask.BUTTON_PRESS_MASK)
            tab_event_box.connect("button-press-event", self._on_tab_clicked, idx)

            tab_label = Gtk.Label()
            tab_label.set_use_markup(True)
            tab_label.set_justify(Gtk.Justification.LEFT)
            tab_label.set_line_wrap(False)
            tab_label.set_selectable(False)
            tab_label.set_margin_top(2)
            tab_label.set_margin_bottom(2)
            tab_label.set_halign(Gtk.Align.START)
            tab_label.set_valign(Gtk.Align.START)
            tab_label.set_ellipsize(Pango.EllipsizeMode.END)
            tab_label.get_style_context().add_class("tab-label")

            pango_markup = tab_format % locals()
            tab_label.set_markup(pango_markup)

            tab_event_box.add(tab_label)
            tab_event_box.show_all()
            self.container.pack_start(tab_event_box, False, False, 0)

    def _on_tab_clicked(self, widget, event, tab_index):
        """Internal handler for tab clicks"""
        if event.button == 1 and self.on_tab_clicked_cb:
            self.on_tab_clicked_cb(tab_index)

    def _on_add_tab_clicked(self, widget, event):
        """Internal handler for add button clicks"""
        if event.button == 1 and self.on_add_tab_cb:
            self.on_add_tab_cb()

class MypixelsWindow:
    def __init__(self, app):
        """Initialize a new window

        Args:
            app: MypixelsApplication instance that owns this window
        """
        self.app = app
        self.config = app.config  # Reference to shared config

        # command to run in new tabs (set by Application)
        self.command = None

        # counter used for tab id's - use app's global counter
        self.counter = app.tab_counter

        # entangled terms for multi term keyboard events (window-specific)
        self.entangled = []

        # create a window to hold the thing
        self.window = Gtk.Window()
        self.window.set_title("mypixels")
        self.window.set_border_width(0)

        self.window.connect("delete-event", self.quit_request)

        self.keybinds = []
        self.keymap = {}
        self.on_tabswitch = False

        # default font size - zero is ignored
        self.fontsize = 0

        # handle config
        self.load_config()

        self.overlay = Gtk.Overlay()

        # Enable RGBA visual for transparency support in overlays
        screen = self.window.get_screen()
        visual = screen.get_rgba_visual()
        if visual:
            self.window.set_visual(visual)

        # Required for transparency to work
        self.window.set_app_paintable(True)

        self.window.add(self.overlay)
        self.overlay.show()

        vbox = Gtk.VBox()
        self.vbox = vbox
        # self.vbox.set_resize_mode(Gtk.RESIZE_IMMEDIATE)
        self.overlay.add(vbox)

        # Initialize tabs dict and entangled list
        self.tabs = {}

        # gtk notebook that holds the vterms
        self.notebook = Gtk.Notebook()
        self.notebook.set_show_tabs(False)

        self.notebook.set_show_border(False)
        self.notebook.set_scrollable(True)
        self.notebook.set_border_width(0)

        self.notebook.connect("page-removed", self.tab_closed)
        self.notebook.connect("switch-page", self.tab_changed)
        self.notebook.connect("page-added", self.tab_opened)
        self.notebook.connect("page-reordered", self.tab_reordered)

        # Create TabList instance
        self.tab_list = TabList(
            self.notebook, self.tabs, self.entangled,
            self.config, lambda: self.on_tabswitch
        )
        self.tab_list.set_callbacks(self.goto_tab, self.new_tab)

        vbox.pack_start(self.notebook, True, True, 0)
        vbox.pack_start(self.tab_list.get_widget(), False, False, 0)

        if self.config["tablist_top"]:
            vbox.reorder_child(self.tab_list.get_widget(), 0)
            vbox.reorder_child(self.notebook, 1)
        else:
            vbox.reorder_child(self.notebook, 1)
            vbox.reorder_child(self.tab_list.get_widget(), 2)

        self.notebook.show()

        self.window.connect("key-press-event", self.key_pressed)
        self.window.connect("key-release-event", self.key_released)
        self.window.connect("configure-event", self.resize_request)

        # window fixup before we create tab
        if not self.config["default_maximize"]:
            self.window.resize(self.config["default_width"], self.config["default_height"])

        # searchbox, if it updates, we update the vtk search
        self.search_entry = Gtk.Entry()

        self.search_entry.set_margin_start(5);
        self.search_entry.set_margin_end(5);
        self.search_entry.set_margin_top(5);
        self.search_entry.set_margin_bottom(5);
        self.search_entry.set_halign(Gtk.Align.START);
        self.search_entry.set_valign(Gtk.Align.END);
        self.search_entry.connect("key-press-event", self.search_key_pressed)
        self.search_entry.connect("focus-out-event", self.search_lose_focus)

        self.overlay.add_overlay(self.search_entry)

        self.vbox.show()
        self.window.show()

        # Maximize after showing the window (GTK requirement)
        if self.config["default_maximize"]:
            self.window.maximize()


        self.notebook.grab_focus()

        self.forcedHideTabs = self.config['tablist_hide']

        # try re-applying the configuration
        self.apply_config()

        # hook up wal palette monitoring
        self.hook_wal_reloads()

        # Tab overview instance (after tabs dict is created)
        self.tab_overview = TabOverview(
            self.window, self.overlay, self.notebook,
            self.tabs, self.entangled, self.config, self
        )

    def transform_keybinds(self):
        # transforms self.keymap ("function->binds") to self.keybinds
        for fn, bind in self.keymap.items():
            func = self.funcmap[fn]
            if isinstance(bind, list) or isinstance(bind, tuple):
                for b in bind:
                   (mods, key) = key_press_parse(b)
                   self.keybinds.append((key, mods, func[0], func[1]))
            else:
                (mods, key) = key_press_parse(bind)
                self.keybinds.append((key, mods, func[0], func[1]))

    def set_funcmap(self):
        self.funcmap = {
            'move_prev_tab':  (self.move_prev_tab, None),
            'move_next_tab':  (self.move_next_tab, None),
            'move_first_tab': (self.move_prev_tab, -1),
            'move_last_tab':  (self.move_next_tab, -1),

            'prev_tab': (self.prev_tab, None),
            'next_tab': (self.next_tab, None),
            'first_tab': (self.prev_tab, -1),
            'last_tab': (self.next_tab, -1),

            'close_tab': (self.close_tab, None),
            'new_tab': (self.new_tab, None),

            'shrink_font': (self.shrink_font, None),
            'enlarge_font': (self.enlarge_font, None),

            'toggle_hide_tabs': (self.toggle_hide_tabs, None),

            'prev_color': (self.switch_group, -1),
            'next_color': (self.switch_group,  1),

            'toggle_entangle': (self.toggle_entangle, None),

            'rename_tab': (self.rename_tab, None),

            'show_search': (self.show_search, None),

            'search_prev': (self.search_advance, False),
            'search_next': (self.search_advance, True),

            'font_selector': (self.font_selector, True),

            'config_reload': (self.reload_config, None),

            'show_tab_overview': (self.show_tab_overview, None),

            'new_window': (self.new_window, None)
        }

        for i in range(0, 10):
            self.funcmap['goto_tab_' + str(i)] = (self.goto_tab, i);

    def write_config(self):
        config_path = Path.home() / '.mypixels'
        with open(config_path, 'w') as f:
            yaml.dump(self.config, f, default_flow_style=False)

    def resize_request(self, wnd, event):
        self.update_tablist()

    def key_pressed(self, wnd, event):
        if event.type == Gdk.EventType.KEY_PRESS:
            # If tab overview is active in standalone mode, handle navigation
            if self.tab_overview.active and self.tab_overview.mode == 'standalone':
                return self.tab_overview.handle_key(event)

            # skim through the bindings
            mods = event.state & Gtk.accelerator_get_default_mod_mask()
            keyval = Gdk.keyval_to_lower(event.keyval)

            # TODO: Could accelerate this by placing the key combination into a dict
            for bind in self.keybinds:
                if (bind[0] == keyval) and (bind[1] == mods):
                    bind[2](bind[3])
                    return True
            if (keyval == self.on_tabswitch_key):
                self.on_tabswitch = True
                self.update_tablist()
                # Show overview in switcher mode when Alt is pressed (if enabled)
                if self.config['tab_overview_on_alt'] and not self.tab_overview.active:
                    self.tab_overview.show(mode='switcher')

        # tangled terminals? if so, propagate
        tabn = self.notebook.get_current_page()
        tab = self.notebook.get_nth_page(tabn)

        if (tab in self.entangled):
            for term in self.entangled:
                term.emit("key-press-event", eventkey2gdkevent(event))
            return True

        return False

    def key_released(self, wnd, event):
        tabn = self.notebook.get_current_page()
        tab = self.notebook.get_nth_page(tabn)

        if (event.type == Gdk.EventType.KEY_RELEASE):
            mods = event.state & Gtk.accelerator_get_default_mod_mask()
            keyval = Gdk.keyval_to_lower(event.keyval)
            if (keyval == self.on_tabswitch_key):
                self.on_tabswitch = False
                self.update_tablist()
                # Hide overview when Alt is released (only if in switcher mode)
                if self.tab_overview.active and self.tab_overview.mode == 'switcher':
                    self.tab_overview.hide()

        if (tab in self.entangled):
            for term in self.entangled:
                term.emit("key-release-event", eventkey2gdkevent(event))
            return True
        return False

    def enlarge_font(self, param):
        self.zoom(True)

    def shrink_font(self, param):
        self.zoom(False)

    def on_scroll(self, widget, event):
        # Handles zoom in / zoom out on Ctrl+mouse wheel
        accel_mask = Gtk.accelerator_get_default_mod_mask()
        if event.state & accel_mask == Gdk.ModifierType.CONTROL_MASK:
            direction = event.get_scroll_deltas()[2]
        if direction > 0:  # scrolling down -> zoom out
            self.zoom(False)
        else:
            self.zoom(True)

    def zoom(self, zoom):
        for idx, tab in enumerate(self.notebook):
            pangodesc = tab.get_font()
            fontsize = pangodesc.get_size()

            if fontsize > Pango.SCALE and not zoom:
                fontsize -= Pango.SCALE
            elif zoom:
                fontsize += Pango.SCALE

            pangodesc.set_size(fontsize)
            self.fontsize=fontsize
            tab.set_font(pangodesc)


    def new_tab(self, command=None, tnext=False, title="", cmd=None):
        # new tab instance
        tab = Vte.Terminal()
        tab.connect("child-exited", self.child_exited)
        tab.connect("eof", self.child_eof)
        tab.connect("window-title-changed", self.window_title_changed)
        tab.connect("scroll-event", self.on_scroll)
#        tab.connect("key-press-event", self.key_pressed)
#        tab.connect("key-release-event", self.key_released)

        tab.set_font(Pango.FontDescription(self.config["term_font"]))
        tab.set_scrollback_lines(self.config['scrollback_lines'])
        tab.search_set_wrap_around(True)

        tab.set_word_char_exceptions("-A-Za-z0-9,./?%&#:_~")
        self.apply_tab_colors(tab)

        tid = self.counter.__next__()

        if self.fontsize:
            pangodesc = tab.get_font()
            pangodesc.set_size(self.fontsize)
            tab.set_font(pangodesc)

        # The empty argv list is a fix for zsh segv...
        command=[Vte.get_user_shell()]
        if (cmd):
            command = cmd
        elif (self.command):
            command=self.command

        tab.spawn_async(
            Vte.PtyFlags.DEFAULT,
            os.environ['HOME'],
            command,
            [],
            GLib.SpawnFlags.DEFAULT,
            None,   # child_setup
            None,   # child_setup_data
            -1,     # timeout (no timeout)
            None,   # cancellable
            None,   # callback (optional)
            None    # user_data (optional)
        )

        tab.show()

#        if (command):
#            tab.feed_child(command)

        self.notebook.insert_page(tab, None, tnext and self.notebook.get_current_page() + 1 or -1)
        self.notebook.set_tab_reorderable(tab, True)

        if not title:
            title = self.config["default_tab_title"]

        self.tabs[tab] = {"title": title, "id": tid}
        self.update_tablist()

        tab.grab_focus()

    def new_window(self, param=None):
        """Create a new window"""
        self.app.new_window()

    def update_tablist(self):
        """Update the tab list display"""
        self.tab_list.update(force_hide=self.forcedHideTabs)



    def next_tab(self, skip=1, move=False):
        """ Focuses next tab. If skip is negative, focuses last tab.
        If move is true, moves the tab to the place (otherwise it just focuses)
        """
        if not skip:
            skip = 1

        ntabs = self.notebook.get_n_pages()

        if (ntabs <= 0):
            return

        if skip < 0:
            tabn = ntabs - 1
        else:
            tabn = (self.notebook.get_current_page() + skip) % ntabs

        self.goto_tab(tabn, move)

    def prev_tab(self, skip=1, move=False):
        """ Focuses previous tab. If skip is negative, focuses first tab.
        If move is true, moves the tab to the place (otherwise it just focuses)
        """
        if not skip:
            skip = 1

        ntabs = self.notebook.get_n_pages()

        if (ntabs <= 0):
            return

        if skip < 0:
            tabn = 0
        else:
            tabn = (self.notebook.get_current_page() - skip) % ntabs

        while (tabn < 0):
            tabn += ntabs

        self.goto_tab(tabn, move)

    def move_next_tab(self, skip=1):
        """ Like next_tab, but moves the current tab to the place """
        self.next_tab(skip, move=True)

    def move_prev_tab(self, skip=1):
        """ Like next_tab, but moves the current tab to the place """
        self.prev_tab(skip, move=True)

    def move_first_tab(self, arg=None):
        self.prev_tab(-1, move=True)

    def move_last_tab(self, arg=None):
        self.next_tab(-1, move=True)

    def highlight_tabs(self, toggle):
        pass

    def goto_tab(self, tabn, move=False):
        if move:
            idx = self.notebook.get_current_page()
            tab = self.notebook.get_nth_page(idx)
            self.notebook.reorder_child(tab, tabn)

        self.notebook.set_current_page(tabn)
        self.update_tablist()

    def toggle_entangle(self, ignored):
        tab = self.get_current_tab()

        if tab in self.entangled:
            self.entangled = filter(lambda t: t != tab, self.entangled)
        else:
            self.entangled.append(tab)

        self.update_tablist()

    def toggle_hide_tabs(self, tabn=None):
        self.forcedHideTabs = not self.forcedHideTabs
        self.update_tablist()

    def close_tab(self, tabn=None):
        # TODO: What if this ended when not a current page?
        if not tabn:
            tabn = self.notebook.get_current_page()
        if (tabn >= 0):
            self.notebook.remove_page(tabn)

    def rename_tab(self, tabn=None):
        if not tabn:
            tabn = self.notebook.get_current_page()

        tab = self.notebook.get_nth_page(tabn)
        name = dialog_get_text(
            self.window, "Tab name", self.tabs[tab].get('name', ''))
        if name:
            self.tabs[tab]['name'] = name
            self.update_tablist()

    def tab_closed(self, notebook, tab, index):
        # Clean up tab data and cache
        if tab in self.tabs:
            del self.tabs[tab]
        self.tab_overview.invalidate_cache(tab)

        if (self.notebook.get_n_pages() == 0):
            self.quit_request()
        else:
            tabn = self.notebook.get_current_page()
            # refocus
            self.notebook.set_current_page(tabn)

        self.update_tablist()


    def child_exited(self, term, status):
        for idx, tab in enumerate(self.notebook):
            if tab == term:
                self.notebook.remove_page(idx)
        self.update_tablist()

    def child_eof(self, a=None, b=None):
        pass

    def window_title_changed(self, term):
        self.tabs[term]['title'] = term.get_property("window-title")
        self.update_tablist()

    def tab_opened(self, notebook, tab, index):
        if self.config["focus_new_tabs"]:
            self.notebook.set_focus_child(tab)
            self.notebook.set_current_page(index)
        else:
            oldindex = self.notebook.get_current_page()

            if oldindex < 0:
                oldindex = index

            oldtab = self.notebook.get_nth_page(oldindex)
            self.notebook.set_focus_child(oldtab)
            self.notebook.set_current_page(oldindex)

        # Refresh overview if active
        if self.tab_overview.active:
            mode = self.tab_overview.mode
            self.tab_overview.hide()
            self.tab_overview.show(mode=mode)

    def tab_changed(self, notebook, tab, index):
        self.update_tablist()

        # Update overview selection if in switcher mode
        if self.tab_overview.active and self.tab_overview.mode == 'switcher':
            # Update selection to highlight current tab immediately
            self.tab_overview.update_selection(index)

            # Capture snapshot with delay to allow terminal to render
            def capture_and_update():
                current_page = self.notebook.get_current_page()
                if current_page >= 0 and current_page == index:  # Still on the same tab
                    tab = self.notebook.get_nth_page(current_page)
                    pixbuf = self.tab_overview.capture_terminal_snapshot(tab)
                    if pixbuf:
                        self.tab_overview.snapshot_cache[tab] = pixbuf
                        # Update the tile image
                        self.tab_overview.update_tile_image(index)
                return False

            GLib.timeout_add(500, capture_and_update)  # 500ms delay for terminal rendering
        else:
            # Normal update with delay when not in switcher mode
            GLib.timeout_add(50, lambda: self.tab_overview.update_snapshot_cache(force=True))

    def tab_reordered(self, notebook, tab, index):
        self.update_tablist()
        # Refresh overview if active in switcher mode
        if self.tab_overview.active and self.tab_overview.mode == 'switcher':
            # Hide and re-show to refresh the grid layout
            self.tab_overview.hide()
            self.tab_overview.show(mode='switcher')

    def switch_group(self, skip):
        tabn = self.notebook.get_current_page()
        tab = self.notebook.get_nth_page(tabn)

        params = self.tabs.setdefault(tab, {})

        grp = params.setdefault("group", 0) + skip

        # if the group goes beyond 0 or max
        if grp < 0:
            grp = max_groups - 1

        if grp >= max_groups:
            grp = 0

        # if the group is zero, remove the def
        # otherwise replace
        if grp == 0:
            del params["group"]
        else:
            params["group"] = grp

        # update tab view
        self.update_tablist()

    def show_search(self, param=None):
        self.search_entry.show()
        self.search_entry.grab_focus()

    def hide_search(self, param=None):
        self.search_entry.hide()

    def search_advance(self, forward=True):
        tab = self.get_current_tab()
        if (forward):
            tab.search_find_next()
        else:
            tab.search_find_previous()

    def font_selector(self, param=None):
        font_chooser = Gtk.FontSelectionDialog("Terminal font", self.window)
        font_chooser.set_font_name(self.config["term_font"])
        res = font_chooser.run()

        if res == Gtk.ResponseType.OK:
            fname = font_chooser.get_font_name()
            font_desc = Pango.FontDescription(fname)
            if font_desc:
                self.config["term_font"] = fname
                for tab in self.tabs:
                    tab.set_font(font_desc)

        font_chooser.destroy()

    def get_current_tab(self):
        tabn = self.notebook.get_current_page()
        return self.notebook.get_nth_page(tabn)

    def search_lose_focus(self, wnd, event):
        self.hide_search()
        # re-focus current tab
        self.get_current_tab().grab_focus()

    def search_key_pressed(self, wnd, event):
        if event.type == Gdk.KEY_PRESS:
            if (event.keyval == Gdk.KEY_Escape):
                self.hide_search()
                return False
            if (event.keyval == Gdk.KEY_Return):
                self.update_search_term(self.search_entry.get_text())
                self.hide_search()
                self.search_advance(True)
                return False
        return False

    def update_search_term(self, text):
        tab = self.get_current_tab()
        regex = GLib.Regex(text, 0, 0)
        tab.search_set_gregex(regex, 0)

    def show_tab_overview(self, param=None):
        """Show tab overview - delegates to TabOverview class"""
        self.tab_overview.show(mode='standalone')

    def run(self):
        """Deprecated - kept for backward compatibility

        The main loop is now handled by MypixelsApplication.
        This method is only called from old code paths.
        """
        # Command args now handled by Application
        self.command = None
        self.new_tab()
        Gtk.main()

    def quit_request(self, *args):
        # if there is more than one tab, ask
        if (self.notebook.get_n_pages() > 1):
            # ask first
            dialog = Gtk.MessageDialog(transient_for=self.window,
                                       modal=True, destroy_with_parent=True,
                                       message_type=Gtk.MessageType.INFO,
                                       buttons=Gtk.ButtonsType.YES_NO,
                                       text="Do you really want to close?")

            rv = dialog.run()
            dialog.destroy()

            if rv != Gtk.ResponseType.YES:
                return True # cancel the quit

        # Cleanup and quit
        # Remove this window from the application
        self.app.remove_window(self)

        # If this was the last window, quit the application
        if len(self.app.windows) == 0:
            self.app.quit()
        else:
            # Just close this window
            self.window.destroy()

        return True  # Prevent default close handler

    def load_config(self):
        config_path = Path.home() / ".mypixels"

        try:
            if not config_path.exists():
                print(f"No config file found at {config_path}, using defaults")
                self.load_wal_palette()
                return

            with open(config_path) as f:
                myconfig = yaml.load(f, Loader=yaml.FullLoader)

            try:
                for k in self.config.keys():
                    # if this is a keymap, descend
                    if k == "bindings":
                        if "bindings" in myconfig:
                            for fn, b in myconfig['bindings'].items():
                                self.config[k][fn] = b
                    else:
                        if k in myconfig:
                            self.config[k] = myconfig[k]
            except Exception as e:
                print(f"Config parse error: {e}")

            # Validate configuration
            validation_warnings = validate_config(self.config)
            if validation_warnings:
                print("Configuration validation warnings:")
                for warning in validation_warnings:
                    print(f"  - {warning}")

        except Exception as e:
            print(f"Error loading config from {config_path}: {e}")
            traceback.print_exc()

        # try to override the colors from wal palette if that is set to be used
        self.load_wal_palette()

    def apply_tab_colors(self, tab):
        bg_color = Gdk.RGBA()
        bg_color.parse(self.config['bg_tint_color'])
        bg_color.alpha=1.0-self.config['term_opacity']

        if self.palette:
            # Apply the same alpha to the palette background color
            transparent_bg = self.bg_color.copy()
            transparent_bg.alpha = 1.0-self.config['term_opacity']
            tab.set_colors(self.fg_color, transparent_bg, self.palette)
        else:
            # No palette, just set foreground and background with transparency
            tab.set_colors(self.fg_color, bg_color, [])

    def apply_config(self):
        # higlights tab nums on press
        self.on_tabswitch_key = key_press_parse(self.config["tab_highlight_mod"])[1]

        # parse the config key bindings
        self.set_funcmap()
        self.keymap = self.config['bindings']
        self.transform_keybinds()

        # convert the call config vars to callables
        if 'palette' in self.config:
            colors = self.config['palette'].split(':')
            self.palette = []
            for color in colors:
                if color:
                    self.palette.append(parse_rgba(color))
        else:
            self.palette = None

        self.fg_color = parse_rgba(self.config['foreground_color'])
        self.bg_color = parse_rgba(self.config['background_color'])

        

        fontdesc = Pango.FontDescription(self.config["tablist_font"])
        font_size_in_pt = fontdesc.get_size() / Pango.SCALE

        bgcolor = self.config['tablist_background']
        # TODO: self.tab_list.get_widget().modify_bg(Gtk.STATE_NORMAL, bgcolor)

        css = f"""
        #tabbar {{
            background-color: {bgcolor};
        }}
        #tabbar GtkEventBox {{ /* Style for individual tab containers */
            padding: 2px 8px; /* Add some padding for visual separation */
            margin-right: 1px; /* Space between tabs */
        }}
        #tabbar .tab-label {{ /* Style for the text within tabs */
            font-family: "{fontdesc.get_family()}";
            font-size: {font_size_in_pt}pt;
        }}
        #tabbar #add-tab-button {{ /* Style for the add tab button */
            background-color: {brighten(bgcolor, 1.1)}; /* Slightly brighter background for the button */
            padding: 2px 8px;
            margin-right: 1px;
        }}
        #tabbar #add-tab-button .tab-label {{ /* Style for the text within the add tab button */
            color: {self.config['add_button_color']};
        }}
        """

        style_provider = Gtk.CssProvider()
        style_provider.load_from_data(css)
        Gtk.StyleContext.add_provider_for_screen(
            Gdk.Screen.get_default(),
            style_provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )

        if self.config["tablist_top"]:
            self.vbox.reorder_child(self.tab_list.get_widget(), 0)
            self.vbox.reorder_child(self.notebook, 1)
        else:
            self.vbox.reorder_child(self.notebook, 1)
            self.vbox.reorder_child(self.tab_list.get_widget(), 2)

        # window fixup before we create tab
        if self.config["default_maximize"]:
            self.window.maximize()
        else:
            self.window.resize(self.config["default_width"], self.config["default_height"])


        # iterate all tabs in our list and re-apply the background
        for idx, tab in enumerate(self.notebook):
            self.apply_tab_colors(tab)

        # repaint the tab bar
        self.update_tablist()

    def reload_config(self, arg=None):
        print("Reloading config...")
        # tries to reload config and re-apply what can be
        self.load_config()
        self.hook_wal_reloads()
        self.apply_config()

    def file_changed(monitor, file, other, unknown, event, self):
        if event == Gio.FileMonitorEvent.CHANGES_DONE_HINT:
           self.load_wal_palette()
           self.apply_config()

    def hook_wal_reloads(self):
        wal_path = Path(self.config['wal_palette']).expanduser()
        self.wal_file = Gio.File.new_for_path(str(wal_path))
        print(f"Will monitor {self.wal_file.get_uri()}")
        self.monitor = self.wal_file.monitor_file(Gio.FileMonitorFlags.NONE, None)
        self.monitor.connect("changed", self.file_changed, self)

    def load_wal_palette(self):
        # if specified in config file, we try to load the yml version of wal palette
        if ('wal_palette' not in self.config) or self.config['wal_palette'] == '':
            print("No wal_palette specified in config. Skipping")
            return

        wal_path = Path(self.config['wal_palette']).expanduser()

        try:
            if not wal_path.exists():
                print(f"Wal palette file not found: {wal_path}")
                return

            with open(wal_path) as f:
                mypal = yaml.load(f, Loader=yaml.FullLoader)
                # special category contains foreground and background
                bgcol  = mypal['special']['background']
                fgcol  = mypal['special']['foreground']
                curcol = mypal['special']['cursor']

                src_cols = mypal['colors']
                colors = []
                for n in range(0, 16):
                      colors.append(src_cols['color' + str(n)])

                # that's all there's to it, really. Now we apply those
                tab_bg = brighten(bgcol, 1.5)

                self.config['background_color']   = bgcol
                self.config['bg_tint_color']      = bgcol
                self.config['foreground_color']   = fgcol

                self.config['tablist_background'] = tab_bg
                self.config['tab_color_bg'] = tab_bg
                self.config['tab_color_bg_selected'] = brighten(tab_bg, 1.5)
                self.config['tab_color_fg'] = fgcol
                self.config['tab_color_fg_selected'] = curcol

                self.config['tab_color_entangle'] = colors[1]
                self.config['tab_color_idx'] = colors[2]

                for n in range(0,8):
                      self.config['col_' + str(n)] = colors[n]

                # and at last, the palette
                self.config['palette'] = ':'.join(colors)

                print("Loaded wal colors")
        except Exception as e:
            exc_info = sys.exc_info()
            traceback.print_exception(*exc_info)
            print("Cannot load/apply wal colors: %s!" % repr(e))

class MypixelsApplication(Gtk.Application):
    """Application-level manager for mypixels

    Manages multiple windows, shared configuration, and D-Bus single-instance detection.
    """

    def __init__(self):
        super().__init__(
            application_id="com.github.volca.mypixels",
            flags=Gio.ApplicationFlags.HANDLES_COMMAND_LINE
        )
        self.windows = []  # List of MypixelsWindow instances
        self.command_args = None
        self.config = config  # Shared config across all windows
        self.tab_counter = counter()  # Global tab ID generator

    def do_activate(self):
        """Called when application is activated (first launch or by remote instance)"""
        # Always create a new window
        self.new_window(self.command_args)

    def new_window(self, command=None):
        """Create a new window

        Args:
            command: Optional command to run in new tabs
        """
        window = MypixelsWindow(self)
        self.windows.append(window)
        self.add_window(window.window)

        # Set command if provided
        if command:
            window.command = command

        # Create first tab
        window.new_tab()

        # Show window
        window.window.present()

    def remove_window(self, window):
        """Remove a window from the application

        Args:
            window: MypixelsWindow instance to remove
        """
        if window in self.windows:
            self.windows.remove(window)

    def do_command_line(self, command_line):
        """Called when mypixels is run again while already running"""
        # Get command line arguments
        argv = command_line.get_arguments()

        # Store args for new window (skip program name)
        if len(argv) > 1:
            self.command_args = argv[1:]
        else:
            self.command_args = None

        # Activate (will create window or bring to front)
        self.activate()

        return 0  # Return 0 for success

def main():
    """Main entry point for mypixels"""
    app = MypixelsApplication()
    exit_status = app.run(sys.argv)
    sys.exit(exit_status)

if __name__ == '__main__':
    main()
